#!/bin/bash

# A simple script for a slightly secure password storage
# file.  Requires gpg and vim.
# by Dan Feerst (feerstd@gmail.com)

homedir="/home/dmf86"
file="$homedir/.secret"
exec="/usr/bin/gpg2"

if [ "$1" == "display" ]; then
    $exec -q --yes -d $file.gpg
    sleep 5
    clear
    rm -f

elif [ "$1" == "open" ]; then
    $exec -q --yes -d $file.gpg > $file
    vim $file

elif [ "$1" == "close" ]; then
    $exec -q --yes --symmetric $file
    echo RELOADAGENT | gpg-connect-agent
    if [[ $file -ot $file.gpg && -a $file.gpg ]]; then
        rm $file
    else
        echo -e "ERROR: Something bad happened"
    fi

elif [ "$1" == "flush" ]; then
    echo RELOADAGENT | gpg-connect-agent

else
    echo -e "ERROR: arguments are \"display\", \"open\", \"flush\", and \"close\"."
fi


