#!/bin/bash

# A simple script for a slightly secure password storage
# file.  Requires gpg and vim.
# by Dan Feerst (feerstd@gmail.com)

# Users home directory
homedir="/home/dmf86"

# Location for plaintext file. Hashfile will append '.gpg'
file="$homedir/.secret"

# gpg location
exec="/usr/bin/gpg2"

# Text editor location
editor="/usr/bin/vim"

# Display sleep time before clearing screen
sleepTime=10
if [ "$1" == "display" ]; then
    $exec -q --yes -d $file.gpg
    sleep $sleepTime
    clear
    rm -f

elif [ "$1" == "open" ]; then
    $exec -q --yes -d $file.gpg > $file
    $editor $file

elif [ "$1" == "close" ]; then
    $exec -q --yes --symmetric $file
    echo RELOADAGENT | gpg-connect-agent
    if [[ $file -ot $file.gpg && -a $file.gpg ]]; then
        rm $file
    else
        echo -e "ERROR: Something bad happened"
    fi

elif [ "$1" == "flush" ]; then
    echo RELOADAGENT | gpg-connect-agent

else
    echo -e "ERROR: arguments are \"display\", \"open\", \"flush\", and \"close\"."
fi


